version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: kaihei-frontend
    restart: always
    network_mode: host
    env_file:
      - ./frontend/.env
  backend:
    build:
      context: ./backend
    container_name: kaihei-backend
    restart: always
    network_mode: host
    env_file:
      - ./backend/.env
