version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "4321:3000"
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "1321:1321"
